# Generated by Django 5.2.8 on 2025-11-13 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompanyInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Company's official name", max_length=255
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Company's logo",
                        null=True,
                        upload_to="logos/",
                    ),
                ),
                ("address", models.TextField(help_text="Company's physical address")),
                (
                    "phone_number",
                    models.CharField(help_text="Contact phone number", max_length=20),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Contact email address", max_length=254
                    ),
                ),
                ("website", models.URLField(help_text="Company's website")),
                (
                    "currency",
                    models.CharField(
                        help_text="Default currency (e.g., USD, SAR)", max_length=10
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="UTC",
                        help_text="Default timezone (e.g., Asia/Riyadh)",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name": "Company Information",
                "verbose_name_plural": "Company Information",
            },
        ),
    ]
